//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статусы.
    /// </summary>
    // *** Start programmer edit section *** (Статусы CustomAttributes)

    // *** End programmer edit section *** (Статусы CustomAttributes)
    public enum Статусы
    {
        
        // *** Start programmer edit section *** (Статусы.2 CustomAttributes)

        // *** End programmer edit section *** (Статусы.2 CustomAttributes)
        [Caption("Исправен")]
        2,
        
        // *** Start programmer edit section *** (Статусы.1 CustomAttributes)

        // *** End programmer edit section *** (Статусы.1 CustomAttributes)
        [Caption("Неисправен")]
        1,
    }
}
